// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb1UW2oF30N08cnv0LmP0BaQVi1D3YMxw',
    appId: '1:23453399326:web:a892936133bc581414b10f',
    messagingSenderId: '23453399326',
    projectId: 'company-driver-dispatch-e28c1',
    authDomain: 'company-driver-dispatch-e28c1.firebaseapp.com',
    storageBucket: 'company-driver-dispatch-e28c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw6c4qKbxaru6jNE4TNZDfO1_o4fj2nUc',
    appId: '1:23453399326:android:e9fbddc44466dcf814b10f',
    messagingSenderId: '23453399326',
    projectId: 'company-driver-dispatch-e28c1',
    storageBucket: 'company-driver-dispatch-e28c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBupR5kczOi6EHkfpV5qhAxVoYcvKGJ1Co',
    appId: '1:23453399326:ios:4f323701b4cd5bfc14b10f',
    messagingSenderId: '23453399326',
    projectId: 'company-driver-dispatch-e28c1',
    storageBucket: 'company-driver-dispatch-e28c1.firebasestorage.app',
    iosBundleId: 'com.example.driverDispatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBupR5kczOi6EHkfpV5qhAxVoYcvKGJ1Co',
    appId: '1:23453399326:ios:4f323701b4cd5bfc14b10f',
    messagingSenderId: '23453399326',
    projectId: 'company-driver-dispatch-e28c1',
    storageBucket: 'company-driver-dispatch-e28c1.firebasestorage.app',
    iosBundleId: 'com.example.driverDispatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb1UW2oF30N08cnv0LmP0BaQVi1D3YMxw',
    appId: '1:23453399326:web:554eb00fcef299ba14b10f',
    messagingSenderId: '23453399326',
    projectId: 'company-driver-dispatch-e28c1',
    authDomain: 'company-driver-dispatch-e28c1.firebaseapp.com',
    storageBucket: 'company-driver-dispatch-e28c1.firebasestorage.app',
  );

}