# platform :ios, '12.0'
platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('..', 'Flutter', 'podhelper'), __FILE__)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end
